services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo_data:/data/db
    networks:
      - free-mentors-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/free_mentors_db?authSource=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=admin@123
      - SECRET_KEY=your-secret-key
    volumes:
      - ./backend:/app
    networks:
      - free-mentors-network

  frontend:
    build: 
      context: ./free-mentors-frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./free-mentors-frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - free-mentors-network

networks:
  free-mentors-network:
    driver: bridge

volumes:
  mongo_data: